import 'package:flutter/material.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../theme/app_theme.dart';
import '../services/patient_data_service.dart';

class ProfileScreen extends StatefulWidget {
  const ProfileScreen({super.key});

  @override
  State<ProfileScreen> createState() => _ProfileScreenState();
}

class _ProfileScreenState extends State<ProfileScreen>
    with SingleTickerProviderStateMixin {
  String _patientName = "Loading...";
  String _patientPhone = "";
  String _patientSummary = "";

  List<String> _history = [];
  List<String> _prescriptions = [];
  List<String> _labs = [];
  List<String> _diet = [];

  bool _isLoading = true;
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 4, vsync: this);
    _loadPatientData();
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  Future<void> _loadPatientData() async {
    final user = FirebaseAuth.instance.currentUser;
    final phone = user?.email?.split('@')[0] ?? "Unknown";

    final contextStr = await PatientDataService.getContextString();

    String name = "Patient";
    if (contextStr.contains("- Name: ")) {
      final start = contextStr.indexOf("- Name: ") + 8;
      final end = contextStr.indexOf("\n", start);
      if (end != -1) name = contextStr.substring(start, end).trim();
    }

    final history = await PatientDataService.getHistory();
    final prescriptions = await PatientDataService.getPrescriptions();
    final labs = await PatientDataService.getLabResults();
    final diet = await PatientDataService.getDietHistory();

    if (mounted) {
      setState(() {
        _patientName = name;
        _patientPhone = phone;
        _patientSummary = contextStr.replaceAll("PATIENT SUMMARY:", "").trim();
        _history = history.reversed.toList();
        _prescriptions = prescriptions;
        _labs = labs.reversed.toList();
        _diet = diet.reversed.toList();
        _isLoading = false;
      });
    }
  }

  void _logout(BuildContext context) async {
    await FirebaseAuth.instance.signOut();
    await PatientDataService.clearLocalData();
    if (context.mounted) {
      Navigator.pushNamedAndRemoveUntil(context, '/', (route) => false);
    }
  }

  Future<void> _generateReport(BuildContext context) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Header(
                level: 0,
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text('MOBILE DOC MEDICAL REPORT',
                        style: pw.TextStyle(
                            fontSize: 20,
                            fontWeight: pw.FontWeight.bold,
                            color: PdfColors.teal)),
                    pw.Text('Date: ${DateTime.now().toString().split(' ')[0]}'),
                  ],
                ),
              ),
              pw.SizedBox(height: 20),
              pw.Text('PATIENT DETAILS',
                  style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold, fontSize: 14)),
              pw.Divider(),
              pw.Text('Name: $_patientName'),
              pw.Text('Phone: $_patientPhone'),
              pw.SizedBox(height: 10),
              pw.Text(_patientSummary.split("ACTIVE MEDICATIONS")[0]),
              pw.SizedBox(height: 20),
              pw.Text('ACTIVE PRESCRIPTIONS',
                  style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold, fontSize: 14)),
              pw.Divider(),
              ..._prescriptions.map((p) =>
                  pw.Text('• $p', style: const pw.TextStyle(fontSize: 10))),
              pw.SizedBox(height: 20),
              pw.Text('RECENT CONSULTATIONS',
                  style: pw.TextStyle(
                      fontWeight: pw.FontWeight.bold, fontSize: 14)),
              pw.Divider(),
              ..._history.take(5).map((entry) => pw.Padding(
                    padding: const pw.EdgeInsets.only(bottom: 8),
                    child: pw.Text('• $entry',
                        style: const pw.TextStyle(fontSize: 10)),
                  )),
              pw.Spacer(),
              pw.Divider(),
              pw.Text('Generated by Dr. Mobile Doc AI System',
                  style:
                      const pw.TextStyle(fontSize: 8, color: PdfColors.grey)),
            ],
          );
        },
      ),
    );

    await Printing.layoutPdf(
        onLayout: (PdfPageFormat format) async => pdf.save());
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("My Profile"),
        backgroundColor: AppColors.primary,
        foregroundColor: Colors.white,
        actions: [
          IconButton(
            icon: const Icon(Icons.refresh),
            onPressed: _loadPatientData,
          )
        ],
        bottom: TabBar(
          controller: _tabController,
          labelColor: Colors.white,
          unselectedLabelColor: Colors.white70,
          indicatorColor: Colors.white,
          tabs: const [
            Tab(text: "History"),
            Tab(text: "Meds"),
            Tab(text: "Labs"),
            Tab(text: "Diet"),
          ],
        ),
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : Column(
              children: [
                // Header
                Container(
                  padding: const EdgeInsets.all(20),
                  color: Colors.grey.shade50,
                  child: Row(
                    children: [
                      const CircleAvatar(
                        radius: 30,
                        backgroundColor: AppColors.secondary,
                        child: Icon(Icons.person,
                            size: 30, color: AppColors.primary),
                      ),
                      const SizedBox(width: 16),
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text(_patientName,
                              style: const TextStyle(
                                  fontSize: 20, fontWeight: FontWeight.bold)),
                          Text(_patientPhone,
                              style: const TextStyle(
                                  fontSize: 14, color: Colors.grey)),
                        ],
                      ),
                      const Spacer(),
                      IconButton(
                        icon: const Icon(Icons.description, color: Colors.blue),
                        tooltip: "Generate Report",
                        onPressed: () => _generateReport(context),
                      )
                    ],
                  ),
                ),

                Expanded(
                  child: TabBarView(
                    controller: _tabController,
                    children: [
                      _buildList(_history, "No consultation history."),
                      _buildPrescriptionsList(),
                      _buildList(_labs, "No lab results recorded."),
                      _buildList(_diet, "No diet scans yet."),
                    ],
                  ),
                ),

                // Logout Footer
                Padding(
                  padding: const EdgeInsets.all(16.0),
                  child: SizedBox(
                    width: double.infinity,
                    child: OutlinedButton.icon(
                      onPressed: () => _logout(context),
                      icon: const Icon(Icons.logout),
                      label: const Text("Sign Out"),
                      style: OutlinedButton.styleFrom(
                        foregroundColor: Colors.red,
                        side: const BorderSide(color: Colors.red),
                      ),
                    ),
                  ),
                ),
              ],
            ),
    );
  }

  Widget _buildList(List<String> items, String emptyMsg) {
    if (items.isEmpty) {
      return Center(
          child: Text(emptyMsg, style: const TextStyle(color: Colors.grey)));
    }
    return ListView.builder(
      padding: const EdgeInsets.all(16),
      itemCount: items.length,
      itemBuilder: (context, index) {
        return Card(
          margin: const EdgeInsets.only(bottom: 8),
          elevation: 0,
          shape: RoundedRectangleBorder(
              side: BorderSide(color: Colors.grey.shade200),
              borderRadius: BorderRadius.circular(8)),
          child: Padding(
            padding: const EdgeInsets.all(12.0),
            child: Text(items[index], style: const TextStyle(fontSize: 13)),
          ),
        );
      },
    );
  }

  Widget _buildPrescriptionsList() {
    if (_prescriptions.isEmpty) {
      return const Center(
          child: Text("No active prescriptions.",
              style: TextStyle(color: Colors.grey)));
    }
    return ListView.builder(
      padding: const EdgeInsets.all(16),
      itemCount: _prescriptions.length,
      itemBuilder: (context, index) {
        return Card(
          margin: const EdgeInsets.only(bottom: 8),
          elevation: 0,
          color: Colors.blue.shade50,
          shape: RoundedRectangleBorder(
              side: BorderSide(color: Colors.blue.shade100),
              borderRadius: BorderRadius.circular(8)),
          child: ListTile(
            leading: const Icon(Icons.medication, color: AppColors.primary),
            title: Text(_prescriptions[index],
                style:
                    const TextStyle(fontSize: 14, fontWeight: FontWeight.w500)),
            trailing: IconButton(
              icon: const Icon(Icons.check_circle_outline, color: Colors.green),
              onPressed: () {
                // Mark as taken or remove
                PatientDataService.removePrescription(index)
                    .then((_) => _loadPatientData());
              },
            ),
          ),
        );
      },
    );
  }
}
